---@type Lazyspec
local spec = {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "html",
        "css",
        "scss",
        "javascript",
        "typescript",
        "tsx",
        "vue",
        "lua",
        "java",
        "vim",
        "xml",
        "yaml",
        "zig",
        "bash",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "dart",
        "csv",
        "dart",
        "json",
        "json5",
        "jsonc",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "graphql",
        "kotlin",
        "llvm",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "rust",
        "proto",
        "rst",
        "sql",
        "ssh_config",
        "strace",
        "swift",
        "svelte",
        "terraform",
        "toml",
        "regex",
        "comment",
        "hcl",
        "jsdoc",
        "luadoc",
      },
      highlight = {
        enable = true,
      },
    })
  end,
}

return spec
